// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import "./globals.css";
// import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Outfit, Roboto_Mono } from "next/font/google";
import NavLink from "./components/navLink";
import Link from "next/link";
import UserLinks from "./components/userLinks";
import { NextAuthProvider } from "./providers";

// const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});
const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Bel Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={`${outfit.variable} ${roboto_mono.variable}`}
      lang="en"
    >
      <body className="bg-slate-100 font-sans">
        {/* <body className={inter.className}> */}
        {/* <AuthContext> */}
        <NextAuthProvider>
          <header>
            <nav className="fixed top-0 z-20 w-full flex items-center bg-transparent text-cyan-800 h-20 pr-10">
              <div className="w-1/3 pl-10">
                <Link
                  href="/"
                  className="font-bold text-3xl text-cyan-500 hover:text-yellow-800"
                >
                  Bel-Sites
                </Link>
              </div>
              <div className="flex justify-evenly w-2/3 text-lg">
                <NavLink href="/">Home</NavLink>
                <NavLink href="/search">Sites</NavLink>
                <UserLinks />
              </div>
            </nav>
          </header>

          <main className="">{children}</main>
        </NextAuthProvider>
        {/* </AuthContext> */}
      </body>
    </html>
  );
}
